name: Oracle Consumer Lastprice USD

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cd oracle-onchain/v2/oracle-consumer-examples/lastprice_usd && cargo llvm-cov --all-features --fail-under-lines 95

